[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
boya = "program_id_here"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/m1721/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
